// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffiNTw96YWJg4thExPgMUV13zZVk3LLs',
    appId: '1:44106493211:android:456b3def54b9ca227737be',
    messagingSenderId: '44106493211',
    projectId: 'pet-social-bfa21',
    storageBucket: 'pet-social-bfa21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7T87Q1KtR7p2YXjcBr2R5nUbhywVLxHM',
    appId: '1:44106493211:ios:bf2d1424cac58bdf7737be',
    messagingSenderId: '44106493211',
    projectId: 'pet-social-bfa21',
    storageBucket: 'pet-social-bfa21.firebasestorage.app',
    iosClientId: '44106493211-d9udshkonss3i4bp9a9lfkkvie2rk4eh.apps.googleusercontent.com',
    iosBundleId: 'com.natderwin.tailsDate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1oUNQ_jAuI2yiSmc5JNJp9W5T5eoJpNc',
    appId: '1:44106493211:web:37e43f2173f543067737be',
    messagingSenderId: '44106493211',
    projectId: 'pet-social-bfa21',
    authDomain: 'pet-social-bfa21.firebaseapp.com',
    storageBucket: 'pet-social-bfa21.firebasestorage.app',
    measurementId: 'G-MCRDLVBBMR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7T87Q1KtR7p2YXjcBr2R5nUbhywVLxHM',
    appId: '1:44106493211:ios:bf2d1424cac58bdf7737be',
    messagingSenderId: '44106493211',
    projectId: 'pet-social-bfa21',
    storageBucket: 'pet-social-bfa21.firebasestorage.app',
    iosClientId: '44106493211-d9udshkonss3i4bp9a9lfkkvie2rk4eh.apps.googleusercontent.com',
    iosBundleId: 'com.natderwin.tailsDate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1oUNQ_jAuI2yiSmc5JNJp9W5T5eoJpNc',
    appId: '1:44106493211:web:c8346b254ec1fcbe7737be',
    messagingSenderId: '44106493211',
    projectId: 'pet-social-bfa21',
    authDomain: 'pet-social-bfa21.firebaseapp.com',
    storageBucket: 'pet-social-bfa21.firebasestorage.app',
    measurementId: 'G-D95T811HH7',
  );

}